dist: bionic

language: python
cache:
  pip: true
  directories:
    - node_modules

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - SQLALCHEMY_DATABASE_URI="sqlite://"
  - SQLALCHEMY_DATABASE_URI="postgres://postgres@localhost/abilian_crm"

services:
  - redis-server

addons:
  postgresql: "9.6"


# Install OS dependencies
before_install:
  - pip install -U pip setuptools poetry
  - pip install -U pip setuptools wheel tox tox-travis poetry

# Install Python dependencies
install:
  - poetry install
  - pip check
  - npm install -g less
  - yarn

# Create DB
before_script:
  - createdb -w -U postgres -E utf-8 abilian_crm

# Run tests
script:
  - pytest -q --cov abilian abilian
  - make lint-python

# Report coverage
after_success:
  - pip install coveralls
  - coveralls
