dist: bionic

language: python
cache:
  pip: true
  directories:
    - node_modules

python:
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - redis-server

addons:
  postgresql: "9.6"


env:
  - SQLALCHEMY_DATABASE_URI="sqlite://"
  - SQLALCHEMY_DATABASE_URI="postgres://postgres@localhost/abilian"

matrix:
  include:
    - python: 3.6
      env: TOXENV=lint

# Install OS dependencies
install:
  - pip install -U pip setuptools wheel tox tox-travis poetry

# Create DB
before_script:
  - createdb -w -U postgres -E utf-8 abilian

# Run tests
script:
  - tox

# Report coverage
#after_success:
#  - pip install coveralls
#  - coveralls

notifications:
  slack:
    rooms:
      - abilian:dTtRD7DHS4Dw3jfRrqytQWU6#code
    on_success: change
    on_failure: always
