dist: xenial

language: python
cache:
  pip: true
  directories:
    - node_modules

python:
  - "2.7"
  - "3.6"
  - "3.7"

env:
  - SQLALCHEMY_DATABASE_URI="sqlite://"
  - SQLALCHEMY_DATABASE_URI="postgres://postgres@localhost/abilian_crm"

services:
  - redis-server

addons:
  postgresql: "9.6"


# Install OS dependencies
before_install:
 - pip install -U pip setuptools

# Install Python dependencies
install:
  - pip install -r requirements.txt
  - pip install -U -r etc/dev-requirements.txt
  - pip check
  - npm install -g less
  - yarn

# Create DB
before_script:
  - createdb -w -U postgres -E utf-8 abilian_crm

# Run tests
script:
  - pytest -q --cov abilian abilian
  - make lint-python

# Report coverage
after_success:
  - pip install coveralls
  - coveralls
