language: python
python:
  - "2.7"

env:
  - SQLALCHEMY_DATABASE_URI="sqlite://"
  - SQLALCHEMY_DATABASE_URI="postgres://postgres@localhost/abilian_crm"

services:
  - redis-server

addons:
  postgresql: "9.3"

cache:
  directories:
    - $HOME/.pip-cache

# Install OS dependencies
before_install:
 - pip install pip>=8.1

# Install Python dependencies
install:
  - pip install -r etc/dev-requirements.txt
  - pip install -e .

# Create DB
before_script:
  - createdb -w -U postgres -E utf-8 abilian_crm

# Run tests
script:
  - py.test --tb=short -q --cov abilian abilian
  - make lint

# Report coverage
after_success:
  - pip install coveralls
  - coveralls

